### ISSUE TITLE
Export tiff stack

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-cuber#77] opened 2019-05-03 11:40 UTC
It would be cool to have another tool that exports a tiff stack from a wkw dataset.

**Comment by philippotto** [comment] 2019-08-02 08:04
@MartinBuessemeyer Isn't this done? Please make sure to always close your issues after you have finished them. You can write `fixes #77` in the corresponding PR and then the issue is closed as soon as your PR is merged.

**Closed** 2019-08-02 11:07 UTC
